let initial = [
    'elefante, elephant',
    'león, lion',
    'hipopótamo, hippopotamus',
    'rinoceronte, rhinoceros',
    'tigre, tiger',
    'alce, moose',
    'oso, bear',
    'llama, llama',
    'cebra, zebra',
    'bisonte, bison',
    'caballo, horse',
    'burro, donkey',
    'oveja, sheep',
    'venado, deer',
    'chivo, goat',
    'jirafa, giraffe',
    'erdo, hog',
    'vaca, cow',
    'perro, dog',
    'gato, cat',
    'venado, deer',
    'mono, monkey',
    'zorro, fox',
    'armadillo, armadillo',
    'tiburón, shark',
    'pez espada, swordfish',
    'anguila, eel',
    'salmón, salmon',
    'raya, stingray',
    'trucha, trout',
    'águila, eagle',
    'loro, parrot',
    'búho, owl',
    'cisne, swan',
    'pájaro carpintero, woodpecker',
    'gaviota, seagull',
    'paloma, dove',
    'colibrí, hummingbird',
    'cuervo, crow',
    'halcón, hawk',
    'pájaro azul, blue jay',
    'petirrojo, robin',
    'gorrión, sparrow',
    'cardenal, cardinal',
    'abeja, bee',
    'mariposa, butterfly',
    'hormiga, ant',
    'mosquito, mosquito',
    'mosca, fly',
    'araña, spider',
    'gusano de seda, caterpillar',
    'libélula, dragonfly',
    'grillo, cricket',
    'saltamontes, grasshopper',
    'mantis, mantis',
    'alacrán, scorpion',
    'cucaracha, cockroach',
    'escarabajo, beetle',
];

export default initial;
